<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '256M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db6134098848');
define('DB_USER', 'fw1239859808');
define('DB_PASSWORD', 'jzuBETF8xw38XLB2xg5bie0rbhXR8L');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'kp_';






/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          '4UpkI<tq|~N?8[x`@!xHUvjn]M]#bsSkWZ7_%VX#euPm)}v#WjUEkaSaJb20bgYy');
define('SECURE_AUTH_KEY',   '!A$/U!Kn:>iQBHaK?tI5(AM!dM!M|l<pw]B{-yVm9<{f26rYnw_LskHewec1hDY5');
define('LOGGED_IN_KEY',     'O`X4cNv<_EWV;ogq!935WtkGUqEes2~yOrozX$k{R!=6)#p*I*[_2Up8,;7aTTi&');
define('NONCE_KEY',         'oLLtlrRRuoZR<0U?$1(A<8JCR-E_`z>9KQ,~J2!{z/`[)nQsvz.j%6%Mc&%#i9O6');
define('AUTH_SALT',         'T?M!3Q+k`MICp~ThGBu1[sK<FjxtBi/cUhvIfSgPqhSig-bM<IzP6oH_dt@eGBPM');
define('SECURE_AUTH_SALT',  'ev=Ug1Qh}jnuAf}iVK3ZzWICf:<wqH(8U-H!Ic|HL?A)b&Ju^<jYE)K$6AL8=zlO');
define('LOGGED_IN_SALT',    'h=Zs!`*c:o,&{0iPYvxP323>g)-V`yplO@Zt6tb@laehdiN=oLUtzcbt;?n7uW@,');
define('NONCE_SALT',        '`v^=Sp09Ws=`Ta0ktd>CqM|X[Id(W#x[adU/u|e{6@_t#t|?)T5R8zmB?7Isx6]J');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', true);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);


/****************************************************************************/
/*                              Custom Content                              */
/****************************************************************************/



/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
